LK: remove VTSS_FEATURE_SERIAL_GPIO
Laika does not have the SGPIO peripheral, remove it.

When compiling with -O0, the following linking errors occur:

./libp64h.so: undefined reference to `vtss_cil_misc_sgpio_event_enable'
./libp64h.so: undefined reference to `vtss_cil_misc_sgpio_event_poll'
./libp64h.so: undefined reference to `vtss_cil_misc_sgpio_conf_set'
./libp64h.so: undefined reference to `vtss_cil_misc_sgpio_read'

This is not catched by CI because it compiles with optimizations which
optimizes away the calls to the vtss_cil_misc_sgpio_* functions because
of VTSS_SGPIO_GROUPS which equals 0.

Also move down a variable in vtss_misc_inst_create() to avoid an unused
variable error.